# Generated by Django 4.2.8 on 2025-11-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='selected_questions',
            field=models.ManyToManyField(blank=True, related_name='attempted_in', to='quiz.question'),
        ),
    ]
