# Generated by Django 4.2.8 on 2025-11-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_examattempt_selected_questions'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['user', '-started_at'], name='quiz_examat_user_id_437be5_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['exam', 'status'], name='quiz_examat_exam_id_0dd676_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['user', 'status'], name='quiz_examat_user_id_bf02b7_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam', 'question_number'], name='quiz_questi_exam_id_123860_idx'),
        ),
        migrations.AddIndex(
            model_name='questionanswer',
            index=models.Index(fields=['exam_attempt', 'is_correct'], name='quiz_questi_exam_at_c803ff_idx'),
        ),
        migrations.AddIndex(
            model_name='questionanswer',
            index=models.Index(fields=['question', 'is_correct'], name='quiz_questi_questio_7599f8_idx'),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['question', 'label'], name='quiz_questi_questio_892286_idx'),
        ),
    ]
