# Generated by Django 5.2.8 on 2025-12-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('taxation', 'Taxation'), ('criminal_law', 'Criminal Law'), ('criminal_practice', 'Criminal Practice'), ('land_law', 'Land Law'), ('solicitors_accounts', 'Solicitors Accounts'), ('professional_ethics', 'Professional Ethics'), ('trusts', 'Trusts'), ('wills', 'Wills')], db_index=True, default='criminal_law', max_length=50),
        ),
    ]
