# Generated by Django 5.2.8 on 2025-12-29 22:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_add_topic_to_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('taxation', 'Taxation'), ('criminal_law', 'Criminal Law'), ('criminal_practice', 'Criminal Practice'), ('land_law', 'Land Law'), ('solicitors_accounts', 'Solicitors Accounts'), ('professional_ethics', 'Professional Ethics'), ('trusts', 'Trusts'), ('wills', 'Wills')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('lives_remaining', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('points_earned', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_streak', models.IntegerField(default=0)),
                ('current_question_index', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=5)),
                ('correct_count', models.IntegerField(default=0)),
                ('wrong_count', models.IntegerField(default=0)),
                ('fifty_fifty_used', models.BooleanField(default=False)),
                ('time_freeze_used', models.BooleanField(default=False)),
                ('question_ids', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topic Quiz Attempt',
                'verbose_name_plural': 'Topic Quiz Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('selected_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('is_correct', models.BooleanField()),
                ('points_earned', models.IntegerField(default=0)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.topicquizattempt')),
            ],
            options={
                'ordering': ['answered_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGameProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('xp', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('xp_to_next_level', models.IntegerField(default=500)),
                ('total_quizzes_completed', models.IntegerField(default=0)),
                ('total_correct_answers', models.IntegerField(default=0)),
                ('total_wrong_answers', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('rank', models.CharField(choices=[('rookie_scholar', 'Rookie Scholar'), ('law_apprentice', 'Law Apprentice'), ('legal_explorer', 'Legal Explorer'), ('case_analyst', 'Case Analyst'), ('statute_sage', 'Statute Sage'), ('justice_seeker', 'Justice Seeker'), ('legal_legend', 'Legal Legend')], default='rookie_scholar', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Game Profile',
                'verbose_name_plural': 'User Game Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='topicquizattempt',
            index=models.Index(fields=['user', '-started_at'], name='quiz_topicq_user_id_e40c55_idx'),
        ),
        migrations.AddIndex(
            model_name='topicquizattempt',
            index=models.Index(fields=['topic', 'status'], name='quiz_topicq_topic_3b64c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topicquizanswer',
            unique_together={('attempt', 'question_id')},
        ),
    ]
