# Generated by Django 5.2.8 on 2026-01-02 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_fix_remaining_chapters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('instructor', models.CharField(max_length=100)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Display order on course listing')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Course',
                'verbose_name_plural': 'Video Courses',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cloudflare_video_id', models.CharField(help_text='Cloudflare Stream video UID', max_length=100, unique=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0, help_text='Order within the course')),
                ('key_topics', models.JSONField(blank=True, default=list, help_text="List of key topics covered, e.g. ['Topic 1', 'Topic 2']")),
                ('thumbnail_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='quiz.videocourse')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos_completed', models.IntegerField(default=0)),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
                ('last_video', models.ForeignKey(blank=True, help_text='Last video the user was watching', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.video')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='quiz.videocourse')),
            ],
            options={
                'verbose_name': 'Course Progress',
                'verbose_name_plural': 'Course Progress',
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_seconds', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='quiz.video')),
            ],
            options={
                'verbose_name': 'Video Progress',
                'verbose_name_plural': 'Video Progress',
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['course', 'order'], name='quiz_video_course__f2a2c7_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['cloudflare_video_id'], name='quiz_video_cloudfl_acaef0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseprogress',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='videoprogress',
            index=models.Index(fields=['user', 'video'], name='quiz_videop_user_id_86e230_idx'),
        ),
        migrations.AddIndex(
            model_name='videoprogress',
            index=models.Index(fields=['user', 'is_completed'], name='quiz_videop_user_id_6aa108_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videoprogress',
            unique_together={('user', 'video')},
        ),
    ]
