# Generated by Django 5.2.8 on 2026-01-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_video_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocourse',
            name='description',
        ),
        migrations.RemoveField(
            model_name='videocourse',
            name='instructor',
        ),
    ]
