# Generated by Django 5.2.8 on 2026-01-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_remove_instructor_description_from_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='bunny_video_id',
            field=models.CharField(blank=True, help_text='Bunny.net Stream video GUID', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_platform',
            field=models.CharField(choices=[('cloudflare', 'Cloudflare Stream'), ('bunny', 'Bunny.net Stream')], default='bunny', help_text='Video hosting platform', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='cloudflare_video_id',
            field=models.CharField(blank=True, help_text='Cloudflare Stream video UID', max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['bunny_video_id'], name='quiz_video_bunny_v_dfd300_idx'),
        ),
    ]
