# Generated by Django 5.2.8 on 2026-01-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_add_bunny_video_support'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocourse',
            options={'ordering': ['category', 'order', 'title'], 'verbose_name': 'Video Course', 'verbose_name_plural': 'Video Courses'},
        ),
        migrations.AddField(
            model_name='videocourse',
            name='category',
            field=models.CharField(choices=[('FLK1', 'FLK1 - Functioning Legal Knowledge 1'), ('FLK2', 'FLK2 - Functioning Legal Knowledge 2')], default='FLK1', help_text='FLK1 or FLK2 classification', max_length=10),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='description',
            field=models.TextField(blank=True, help_text='Course description'),
        ),
    ]
