# Generated by Django 5.2.8 on 2026-01-03 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_chatconversation_chatmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextbookProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.IntegerField(default=1)),
                ('total_pages', models.IntegerField(default=1)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='quiz.textbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbook_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Textbook Progress',
                'verbose_name_plural': 'Textbook Progress',
                'unique_together': {('user', 'textbook')},
            },
        ),
    ]
