# Generated by Django 5.2.8 on 2026-01-05 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_add_textbook_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('FLK1', 'FLK1 - Functioning Legal Knowledge 1'), ('FLK2', 'FLK2 - Functioning Legal Knowledge 2')], default='FLK1', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📝', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Summary Notes',
                'verbose_name_plural': 'Summary Notes',
                'ordering': ['category', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SummaryNotesChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary_notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='quiz.summarynotes')),
            ],
            options={
                'verbose_name': 'Summary Notes Chapter',
                'verbose_name_plural': 'Summary Notes Chapters',
                'ordering': ['summary_notes', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SummaryNotesProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_chapters', models.JSONField(default=list)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_readers', to='quiz.summarynoteschapter')),
                ('summary_notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='quiz.summarynotes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_notes_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Summary Notes Progress',
                'verbose_name_plural': 'Summary Notes Progress',
                'unique_together': {('user', 'summary_notes')},
            },
        ),
    ]
