# Generated by Django 5.2.8 on 2026-01-05 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_summary_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('FLK1', 'FLK1 - Functioning Legal Knowledge 1'), ('FLK2', 'FLK2 - Functioning Legal Knowledge 2'), ('BOTH', 'Both FLK1 and FLK2')], default='FLK1', max_length=10)),
                ('icon', models.CharField(default='📚', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Flashcard Deck',
                'verbose_name_plural': 'Flashcard Decks',
                'ordering': ['category', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('hint', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='quiz.flashcarddeck')),
            ],
            options={
                'verbose_name': 'Flashcard',
                'verbose_name_plural': 'Flashcards',
                'ordering': ['deck', 'order'],
                'unique_together': {('deck', 'order')},
            },
        ),
        migrations.CreateModel(
            name='FlashcardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards_studied', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('last_studied_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='quiz.flashcarddeck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flashcard Progress',
                'verbose_name_plural': 'Flashcard Progress',
                'unique_together': {('user', 'deck')},
            },
        ),
    ]
