# Generated by Django 5.2.8 on 2026-01-07 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_flashcarddeck_flashcard_flashcardprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeQuestionCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Practice Question Course',
                'verbose_name_plural': 'Practice Question Courses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PracticeQuestionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('area_count', models.PositiveIntegerField(default=0)),
                ('question_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='quiz.practicequestioncourse')),
            ],
            options={
                'verbose_name': 'Practice Question Topic',
                'verbose_name_plural': 'Practice Question Topics',
                'ordering': ['course', 'name'],
                'unique_together': {('course', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='PracticeQuestionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=200)),
                ('question_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='quiz.practicequestiontopic')),
            ],
            options={
                'verbose_name': 'Practice Question Area',
                'verbose_name_plural': 'Practice Question Areas',
                'ordering': ['topic', 'letter'],
                'unique_together': {('topic', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='PracticeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.PositiveIntegerField(help_text='Original question ID from JSON')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('text', models.TextField()),
                ('options', models.JSONField(help_text='List of answer options [{label, text}, ...]')),
                ('correct_answer', models.CharField(max_length=1)),
                ('explanation', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.practicequestionarea')),
            ],
            options={
                'verbose_name': 'Practice Question',
                'verbose_name_plural': 'Practice Questions',
                'ordering': ['area', 'question_id'],
                'indexes': [models.Index(fields=['area', 'question_id'], name='quiz_practi_area_id_21941e_idx'), models.Index(fields=['difficulty'], name='quiz_practi_difficu_577d18_idx')],
                'unique_together': {('area', 'question_id')},
            },
        ),
    ]
