# Generated by Django 6.0 on 2026-01-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_practice_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.CharField(choices=[('FLK1', 'FLK 1'), ('FLK2', 'FLK 2')], default='FLK1', max_length=10),
        ),
    ]
