# Generated by Django 6.0 on 2026-01-12 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_exam_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='passing_score_percentage',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='topicquizattempt',
            name='topic',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
