# Generated by Django 6.0 on 2026-01-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_alter_exam_passing_score_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='cdn_url',
            field=models.URLField(blank=True, help_text='CDN URL for the PDF file (e.g., from Bunny.net)', max_length=500, null=True),
        ),
    ]
