# Generated by Django 6.0 on 2026-01-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_billing_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='questions_snapshot',
            field=models.JSONField(blank=True, help_text='Pre-serialized question data for fast loading', null=True),
        ),
    ]
