# Generated by Django 6.0 on 2026-01-28 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_add_questions_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicquizattempt',
            name='questions_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='passing_score_percentage',
            field=models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
