# Generated by Django 6.0 on 2026-01-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_topicquizattempt_questions_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicquizattempt',
            name='correct_answers',
            field=models.JSONField(default=dict),
        ),
    ]
