export const INSPIRATIONAL_QUOTES = [
    "Calm your mind, and clarity will follow.",
    "Even in quiet moments, progress is happening.",
    "Take a deep breath; every challenge has a solution.",
    "Peace comes when you focus on what you can control.",
    "Slow down; growth cannot be rushed.",
    "Rest is part of progress, not a pause from it.",
    "When pressure mounts, pause and reset.",
    "A clear mind sees paths where confusion hides obstacles.",
    "Stillness can reveal the next right step.",
    "Balance effort with rest, and strength will endure.",
    "Gentle persistence outweighs frantic rushing.",
    "Moments of calm are seeds for tomorrow’s success.",
    "Patience with yourself is as important as discipline.",
    "Let go of what you cannot change; peace will follow.",
    "Take time to breathe; even storms eventually pass.",
    "Gentle steps forward are better than rushed leaps.",
    "Release worry, focus on action, and find calm.",
    "The mind that rests sees solutions more clearly.",
    "Stillness in your day brings clarity to your path.",
    "Peace grows when you focus on what truly matters.",
    "Step back, breathe, and let calm guide your decisions.",
    "Even small pauses refresh the spirit for big challenges.",
    "Courage grows with every small step you take.",
    "Wisdom comes to those who keep learning.",
    "Obstacles are opportunities in disguise.",
    "Every effort counts, no matter how small.",
    "Trust the process, and keep moving forward.",
    "Difficult days often lead to stronger tomorrows.",
    "Hold on to hope, even when the path is unclear.",
    "Small victories build the foundation for great success.",
    "The journey matters as much as the destination.",
    "Encouragement often comes from your own persistence.",
    "Each day brings a chance to grow.",
    "Rise each day with purpose; progress follows intention.",
    "Your effort today plants seeds for tomorrow’s success.",
    "Great achievements start with small, steady actions.",
    "Hope lights the way when the journey feels long.",
    "Keep moving forward; persistence always yields results.",
    "Trust that each step, however small, matters.",
    "Challenges are invitations to discover your strength.",
    "Every day brings a chance to grow beyond yesterday.",
    "Your consistency writes the story of your success.",
    "Strength builds when you embrace each challenge with courage.",
    "Challenges are temporary; perseverance lasts.",
    "Strength is found when you refuse to give up.",
    "Even the longest path begins with a single step.",
    "Consistency builds the bridge to achievement.",
    "Patience in preparation creates confidence in performance.",
    "The smallest victories pave the way to the greatest successes.",
    "Strength grows when you keep going despite fear.",
    "When the way is tough, steady determination wins.",
    "Endurance is the quiet companion of success.",
    "Push forward, even if progress feels invisible.",
    "Obstacles are the stepping stones to growth.",
    "Keep going; your effort shapes your future.",
    "A steady mind is the foundation of success.",
    "Renew your energy, and approach each challenge with purpose.",
    "Clarity comes to those who center themselves.",
    "Direct your attention to what matters most.",
    "Focus on the next step, not the whole journey.",
    "Distraction fades when determination takes hold.",
    "Concentration turns small actions into great achievements.",
    "Set your mind, then let action follow.",
    "The present moment is where progress begins.",
    "Discipline shapes what talent alone cannot.",
    "Purposeful effort outlasts hurried attempts.",
    "Attention to detail builds unshakable confidence.",
    "Your focus today creates your success tomorrow.",
    "A moment may feel heavy, but it will pass. Take one breath at a time.",
    "You cannot control everything; focus on what you can influence.",
    "Even in the storm, small steps forward matter.",
    "It’s okay to pause, reflect, and regain your balance.",
    "Let go of what you cannot change, and make peace with today.",
    "Take things one task, one moment at a time.",
    "Challenges are temporary; your strength is lasting.",
    "Breathe deeply, clarity comes when your mind is still.",
    "Even when life feels chaotic, you can find calm within.",
    "Focus on the present; tomorrow will handle itself.",
    "Even when it feels overwhelming, things are slowly falling into place.",
    "This struggle does not define you; your courage does.",
    "Every challenge is an opportunity to grow stronger and wiser.",
    "Difficult moments often lead to breakthroughs you can’t see yet.",
    "You are resilient, this too shall pass.",
    "Hope is alive even when the path seems unclear.",
    "Be encouraged! progress is happening even if it’s unseen.",
    "Every small effort builds a better tomorrow.",
    "Your current difficulties do not overshadow the good ahead.",
    "Even in the hardest times, there is space to breathe and heal.",
    "Focus on what you can do today, and leave the rest for later.",
    "Even with challenges around you, your work and efforts still matter.",
    "You can move forward despite the chaos.",
    "Do what you can; don’t carry the weight of everything at once.",
    "Small, steady actions create stability in uncertain times.",
    "Concentrate on one step, one task, one solution at a time.",
    "Your mind will be clearer after moments of rest and reflection.",
    "Focus on progress, not the problems that feel too big to solve.",
    "Even amidst difficulties, your dedication makes a difference.",
    "Keep your attention on what you can influence; the rest will unfold in time.",
    "Every hour you’ve studied is building the confidence you need to succeed.",
    "You are prepared more than you realize, trust the work you’ve put in.",
    "Small steps each day lead to big achievements on exam day.",
    "Your effort and consistency are stronger than any exam challenge.",
    "Focus on what you know; you’ve already built a strong foundation.",
    "Doubt is natural, but your preparation is real, trust it.",
    "You’ve faced challenges before and overcome them; this exam is no different.",
    "Stay steady, stay focused, and the results will reflect your hard work.",
    "Your dedication will carry you through, believe in your progress."
]
